source/account/urls.py
from django.urls import path

from account.views import UserDetailView, LoginView, LogoutView, SignUpView

app_name = "account"
urlpatterns = [
    path("profile/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("login/", LoginView.as_view(next_page="front_page:task_of_day"), name="login"),
    path("logout/", LogoutView.as_view(next_page="front_page:task_of_day"), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

source/source/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("front_page.urls")),
    
]

source/templates/generic_base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}365 Python{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.0/prism.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.0/themes/prism.min.css">
    <script src="https://kit.fontawesome.com/dc242f27e3.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="center-header-div">
            <h1>
                365 Python
            </h1>
        </div>
        <div class="right-header-div">
            {% if user.is_authenticated %}
            <a href="{% url 'account:user_detail' pk=user.pk %}">
                <div class="profile-div">
                    <img src="{% static user.get_safe_image_url %}" alt="User Avatar" class="rounded-image">
                    <p class="gray-small-text">{{ user }}</p>
                </div>
            </a>
                <a href="{% url 'account:logout' %}" class="auth-btn">Log out</a>
            {% else %}
                <a href="{% url 'account:login' %}" class="auth-btn">Login</a>
                <a href="{% url 'account:signup' %}" class="auth-btn">Sign up</a>
            {% endif %}
        </div>
    </header>
    <nav>
        <ul>
        </ul>
    </nav>
    <main>
        <div class="container">
            <div class="left-div">
                {% block left_content %}
                {% endblock %}
            </div>
            <div class="right-div">
                {% block right_content %}
                {% endblock %}
            </div>
        </div>
          
    </main>
    <footer>
        &copy; {{ year }} My Website
    </footer>
</body>
</html>