source/account/urls.py
from django.urls import path

from account.views import UserDetailView, LoginView, LogoutView, SignUpView

app_name = "account"
urlpatterns = [
    path("profile/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("login/", LoginView.as_view(next_page="front_page:task_of_day"), name="login"),
    path("logout/", LogoutView.as_view(next_page="front_page:task_of_day"), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

source/front_page/urls.py
from django.urls import path

from front_page.views import (
    TaskDetailView, 
    RunCodeView, 
    SolutionListView, 
    SolutionDetailView,
    CommentListView,
)

app_name = "front_page"
urlpatterns = [
    path("task-of-day/", TaskDetailView.as_view(), name="task_of_day"),   
    path("run-code/", RunCodeView.as_view(), name="run_code"),   
    path("solution-list/", SolutionListView.as_view(), name="solution_list"),
    path("solution-list/<int:pk>/", SolutionDetailView.as_view(), name="solution_detail"),
    path("solution-list/<int:pk>/", SolutionDetailView.as_view(), name="solution_detail"),
    path("comment-list/", CommentListView.as_view(), name="comment_list"),

]

source/source/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path("", include("front_page.urls")),
    
]

source/front_page/models/comment.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models


class Comment(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, db_index=True, editable=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    comment = models.TextField()
    task = models.ForeignKey("front_page.Task", null=True, blank=True, on_delete=models.CASCADE)
    solution = models.ForeignKey("front_page.Solution", null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    edited = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.user} - {self._get_detail}"

    @property
    def _get_detail(self) -> str:
        if self.task or self.solution:
            return f"{self.task or self.solution}"
        return "Invalid comment"

    @property
    def get_reaction(self) -> int:
        from front_page.models import Dislike, Like

        like = Like.objects.filter(comment=self).count()
        dislike = Dislike.objects.filter(comment=self).count()

        return like - dislike

source/front_page/models/dislike.py
from django.contrib.auth import get_user_model
from django.db import models


class Dislike(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    task = models.ForeignKey("front_page.Task", null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey("front_page.Comment", null=True, blank=True, on_delete=models.CASCADE)
    solution = models.ForeignKey("front_page.Solution", null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        indexes = [
            models.Index(fields=["task"]),
            models.Index(fields=["comment"]),
            models.Index(fields=["solution"]),
        ]

source/front_page/models/like.py
from django.contrib.auth import get_user_model
from django.db import models


class Like(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    task = models.ForeignKey("front_page.Task", null=True, blank=True, on_delete=models.CASCADE)
    comment = models.ForeignKey("front_page.Comment", null=True, blank=True, on_delete=models.CASCADE)
    solution = models.ForeignKey("front_page.Solution", null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        indexes = [
            models.Index(fields=["task"]),
            models.Index(fields=["comment"]),
            models.Index(fields=["solution"]),
        ]

source/front_page/models/solution.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import QuerySet
from pygments.lexers import get_lexer_by_name
from front_page.models import Comment
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter
from pygments.styles import get_style_by_name

class Solution(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, db_index=True, editable=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    solution = models.TextField()
    task = models.ForeignKey("front_page.Task", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user.get_username()} - {self.task.summary}"

    @classmethod
    def get_today_solutions(cls, task):
        return cls.objects.filter(task=task)

    @property
    def get_reaction(self) -> int:
        from front_page.models import Dislike, Like

        like = Like.objects.filter(solution=self).count()
        dislike = Dislike.objects.filter(solution=self).count()

        return like - dislike

    def get_comments(self) -> QuerySet[Comment]:
        return Comment.objects.filter(solution=self).order_by("-created_at")

    @property
    def python_syntax_highlighted_code(self):        
        code = highlight(self.solution, PythonLexer(), HtmlFormatter(style="abap"))
        return code

source/front_page/models/task.py
from datetime import datetime
import uuid

from django.db import models
from django.db.models import QuerySet

from front_page.models import Comment, Solution


class Task(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, db_index=True, editable=False)
    summary = models.CharField(max_length=128)
    task = models.TextField()
    date_of_task = models.DateField()

    def __str__(self) -> str:
        return self.summary

    @classmethod
    def get_today_task(cls):
        return cls.objects.get(date_of_task=datetime.today())

    @property
    def get_reaction(self) -> int:
        from front_page.models import Dislike, Like

        like = Like.objects.filter(task=self).count()
        dislike = Dislike.objects.filter(task=self).count()

        return like - dislike

    def get_comments(self) -> QuerySet[Comment]:
        return Comment.objects.filter(task=self).order_by("-created_at")

    def get_solutions(self) -> QuerySet[Solution]:
        return Solution.objects.filter(task=self)

source/front_page/views/comment_view.py
import json

from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseForbidden, HttpResponse

from front_page.models import Comment, Solution


@method_decorator(csrf_exempt, name="dispatch")
class CommentListView(ListView):       
    def post(self, request, *args, **kwargs):
        user = request.user
        
        if not request.user.is_authenticated:
            return HttpResponseForbidden("User is not authenticated.")
        
        data = json.loads(request.body.decode("utf-8"))
        comment = data.get("comment", "")
        solution_id = data.get("solution_id", "")
        
        comment = Comment.objects.create(
            user=user,
            solution=Solution.objects.get(id=solution_id),
            comment=comment,
        )

        data = {
            "user": comment.user.email,
            "time": comment.created_at.strftime("%b. %d, %Y, %I:%M %p").replace("AM", "a.m.").replace("PM", "p.m.")
        }
        return HttpResponse(data=data, status=201)

source/front_page/views/run_code.py
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
import subprocess
from django.http import JsonResponse
import json

@method_decorator(csrf_exempt, name="dispatch")
class RunCodeView(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body.decode("utf-8"))
        code = data.get("code", "")
        
        try:
            result = subprocess.run(
                ["python3", "-c", code],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            if result.returncode == 0:
                output = result.stdout
            else:
                output = result.stderr

            return JsonResponse({"output": output})
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)

source/front_page/views/solutions_view.py
import json
from typing import Any

from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseForbidden

from front_page.models import Task, Solution, Like

@method_decorator(csrf_exempt, name="dispatch")
class SolutionListView(ListView):
    model = Solution
    template_name = "front_page/solution_list.html"
    context_object_name = "solutions"

    def get_queryset(self):
        return Solution.get_today_solutions(Task.get_today_task())
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        user = self.request.user
        if user.is_authenticated:
            context["liked_solution"] = Like.objects.filter(
                user=user,
                solution__task=Task.get_today_task(),
            ).values_list("solution__id", flat=True)

        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden("User is not authenticated.")

        data = json.loads(request.body.decode("utf-8"))
        solution_id = data.get("solution_id", "")
        
        user = request.user
        solution = Solution.objects.get(id=solution_id)
        Like.objects.create(
            user=user,
            solution=solution
        )
        
        number_of_like = Like.objects.filter(solution=solution).count()
        
        return JsonResponse({"output": number_of_like}, status=201)


class SolutionDetailView(DetailView):
    model = Solution

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            context["liked_solution"] = Like.objects.filter(
                user=user,
                solution__task=Task.get_today_task(),
            ).values_list("solution__id", flat=True)
        
        return context

source/front_page/views/task_view.py
import json

from django.contrib.auth import get_user_model
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from front_page.models import Task, Solution


@method_decorator(csrf_exempt, name="dispatch")
class TaskDetailView(TemplateView):
    template_name = "front_page/task_detail.html"
    
    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)

        try:
            context["task"] = Task.get_today_task()
        except Task.DoesNotExist:
            raise ValueError("Task for today not found!")

        return context
    
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body.decode("utf-8"))
        code = data.get("code", "")
        
        # TODO get logged user
        user = get_user_model().objects.first()
        
        Solution.objects.create(
            user=user,
            task=Task.get_today_task(),
            solution=code,
        )

        return HttpResponse({"data": "success"}, status=201)

source/templates/front_page/solution_detail.html
{% extends "../generic_base.html" %}

{% load static %}

{% block title %}{{ task.summary }}{% endblock %}

{% block left_content %}
    <left_h1>{{ task.summary }}</left_h1>
    <p class="scrollable-paragraph-90">{{ task.task }}</p>
{% endblock %}
{% block right_content %}

    <div class="solution_box">
        <a href="{% url 'account:user_detail' pk=object.user.pk %}">
            <p class="gray-small-text">{{ object.user }}</p>
        </a>
        <hr class="styled-line">
        <div class="solution-text-box">
            {{ object.python_syntax_highlighted_code|safe }}
        </div>
        <hr class="styled-line">
        <div class="horizontal-container">
            <div class="horizontal-container">
                <button 
                    class="like-button" 
                    id="like_button_{{ object.id }}" 
                    data-solution-id="{{ object.id }}" 
                    {% if object.id in liked_solution %}disabled{% endif %}
                >
                    <p class="gray-small-text">Like</p>
                </button>
                <p class="gray-small-text" id="reaction_{{ object.id }}">{{ object.get_reaction }}</p>
            </div>
            <div class="element-right"><p class="gray-small-text">{{ object.created_at }}</p></div>
        </div>
    </div>
    <div class="post_comment_box">
        <textarea rows="5" id="comment-text" placeholder="Add comment..."></textarea>
        <button onclick="postComment('{{ object.id }}')" id="post-comment-button" class="post-comment-button">POST</button>
    </div>
    <div id="comment_box" class="comment_box">
        {% for comment in object.comment_set.all %}
            <div>
                <p class="gray-small-text">{{ comment.user }} - {{ comment.created_at }}</p>
                <p class="comment-text">{{ comment.comment }}</p>
            </div>
        {% endfor %}
    </div>
    <script src="{% static 'script/solution_reaction.js' %}"></script>
    <script src="{% static 'script/post_comment.js' %}"></script>

{% endblock %}

source/templates/front_page/solution_list.html
{% extends "../generic_base.html" %}

{% load static %}

{% block title %}{{ task.summary }}{% endblock %}

{% block left_content %}
    <left_h1>{{ task.summary }}</left_h1>
    <p class="scrollable-paragraph">{{ task.task }}</p>
{% endblock %}
{% block right_content %}

    <right_h1>Browse best solutions</right_h1>
    {% for solution in solutions %}
    <div class="solution_box">
        <a href="{% url 'account:user_detail' pk=solution.user.pk %}">
            <p class="gray-small-text">{{ solution.user }}</p>
        </a>
        <hr class="styled-line">
        <div class="solution-text-box">
            {{ solution.python_syntax_highlighted_code|safe }}
        </div>
            
            <hr class="styled-line">
            <div class="horizontal-container">
                <div class="horizontal-container">
                    <button 
                        class="like-button" 
                        id="like_button_{{ solution.id }}" 
                        data-solution-id="{{ solution.id }}" 
                        {% if solution.id in liked_solution %}disabled{% endif %}
                    >
                        <p class="gray-small-text">Like</p>
                    </button>
                    <p class="gray-small-text" id="reaction_{{ solution.id }}">{{ solution.get_reaction }}</p>
                     <a href="http://localhost:8000/solution-list/{{ solution.id }}/" style="text-decoration: none; color: inherit;">
                        <p class="gray-small-text">Solution detail</p>
                    </a>
                    <!-- 
                        <button id="add_comment" class="just-text-button" data-solution-id="{{ solution.id }}">
                            <p class="gray-small-text">Add comment</p>
                        </button> 
                    -->
                </div>
                <div class="element-right"><p class="gray-small-text">{{ solution.created_at }}</p></div>
            </div>
        </div>

    {% endfor %}
    <script src="{% static 'script/solution_reaction.js' %}"></script>
{% endblock %}

source/templates/front_page/task_detail.html
{% extends "../generic_base.html" %}

{% load static %}

{% block title %}{{ task.summary }}{% endblock %}

{% block left_content %}
    <left_h1>{{ task.summary }}</left_h1>
    <p class="scrollable-paragraph-90">{{ task.task }}</p>
{% endblock %}
{% block right_content %}

    <right_h1>Your code...</right_h1>
    <div id="editor"></div>
    <div id="buttons_div"> <button id="run_button" type="button">Run!</button>  <button id="commit_button" type="button">Commit!</button> </div>
    <p id="console_log" class="scrollable-paragraph-90"></p>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.31.1/ace.js"></script>
    <script src="{% static 'script/ace_ide_editor.js' %}"></script>
    <script src="{% static 'script/post_solution.js' %}"></script>
{% endblock %}